### ISSUE TITLE
AttributeError: module 'wandb.proto.wandb_internal_pb2' has no attribute 'Result'

### ISSUE THREAD

**Issue by NeoAnthropocene** [ToTheBeginning/PuLID#128]
I have a problem with the [PuLID Flux](https://github.com/ToTheBeginning/PuLID) build after I instaleld the [LLM party custom node](https://github.com/heshengtao/comfyui_LLM_party).

Do you guys have any idea why it happens?

```
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-21 13:31:49.295943
** Platform: Windows
** Python version: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Total VRAM 16376 MB, total RAM 32517 MB
pytorch version: 2.4.1+cu124
xformers version: 0.0.28.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
Using xformers cross attention
```

```
Traceback (most recent call last):
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\__init__.py", line 1, in <module>
    from .pulidflux import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\pulidflux.py", line 15, in <module>
    from .eva_clip.constants import OPENAI_DATASET_MEAN, OPENAI_DATASET_STD
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\eva_clip\__init__.py", line 2, in <module>
    from .factory import create_model, create_model_and_transforms, create_model_from_pretrained, get_tokenizer, create_transforms
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\eva_clip\factory.py", line 12, in <module>
    from .model import CLIP, CustomCLIP, convert_weights_to_lp, convert_to_custom_text_state_dict,\
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\eva_clip\model.py", line 20, in <module>
    from .timm_model import TimmModel
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\eva_clip\timm_model.py", line 12, in <module>
    import timm
  File "F:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\timm\__init__.py", line 3, in <module>
    from .models import create_model, list_models, list_pretrained, is_model, list_modules, model_entrypoint, \
  File "F:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\timm\models\__init__.py", line 1, in <module>
    from .beit import *
  File "F:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\timm\models\beit.py", line 49, in <module>
    from timm.data import IMAGENET_DEFAULT_MEAN, IMAGENET_DEFAULT_STD
  File "F:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\timm\data\__init__.py", line 5, in <module>
    from .dataset import ImageDataset, IterableImageDataset, AugMixDataset
  File "F:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\timm\data\dataset.py", line 13, in <module>
    from .readers import create_reader
  File "F:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\timm\data\readers\__init__.py", line 1, in <module>
    from .reader_factory import create_reader
  File "F:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\timm\data\readers\reader_factory.py", line 4, in <module>
    from .reader_image_folder import ReaderImageFolder
  File "F:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\timm\data\readers\reader_image_folder.py", line 11, in <module>
    from timm.utils.misc import natural_key
  File "F:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\timm\utils\__init__.py", line 16, in <module>
    from .summary import update_summary, get_outdir
  File "F:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\timm\utils\summary.py", line 9, in <module>
    import wandb
  File "F:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\wandb\__init__.py", line 27, in <module>
    from wandb import sdk as wandb_sdk
  File "F:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\wandb\sdk\__init__.py", line 25, in <module>
    from .artifacts.artifact import Artifact
  File "F:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\wandb\sdk\artifacts\artifact.py", line 36, in <module>
    from wandb.apis.normalize import normalize_exceptions
  File "F:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\wandb\apis\__init__.py", line 43, in <module>
    from .internal import Api as InternalApi  # noqa
  File "F:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\wandb\apis\internal.py", line 3, in <module>
    from wandb.sdk.internal.internal_api import Api as InternalApi
  File "F:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\wandb\sdk\internal\internal_api.py", line 48, in <module>
    from ..lib import retry
  File "F:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\wandb\sdk\lib\retry.py", line 17, in <module>
    from .mailbox import ContextCancelledError
  File "F:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\wandb\sdk\lib\mailbox.py", line 102, in <module>
    class _MailboxSlot:
  File "F:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\wandb\sdk\lib\mailbox.py", line 103, in _MailboxSlot
    _result: Optional[pb.Result]
AttributeError: module 'wandb.proto.wandb_internal_pb2' has no attribute 'Result'

Cannot import F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux module for custom nodes: module 'wandb.proto.wandb_internal_pb2' has no attribute 'Result'
```

**Comment by NeoAnthropocene** [comment]
I re-installed the wandb and protobuf with the required versions and that fixed my problem.

👉 As a side note:
⚠ be careful when installing other nodes (especially hefty ones like [LLM Party](https://github.com/heshengtao/comfyui_LLM_party)), that may break your working virtual environment. Always have a back up.
