### ISSUE TITLE
[bug report] PuLID flux,  "upsample_nearest2d_out_frame" not implemented for 'BFloat16'

### ISSUE THREAD

**Issue by cqflgl** [ToTheBeginning/PuLID#135]
1. envoriment
GPU: A40(48GB),   CPU:  15 vCPU AMD EPYC 7543 32-Core Processor,   Memory: 80GB

**conda activate PuLID,   pip show torch**
Name: torch
Version: 2.0.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /root/miniconda3/envs/PuLID/lib/python3.10/site-packages

**nvidia-smi**
Sun Oct 27 12:39:03 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A40          On   | 00000000:C1:00.0 Off |                  Off |
|  0%   25C    P8    20W / 300W |      0MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
  
**nvcc --version**                                                                            
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

2. configuration of PuLID flux
args.fp8 = True
args.offload = False  
args.onnx_provider = "gpu"  
args.aggressive_offload = False 
num_steps = 20 
seed = -1
start_step = 0 
guidance = 4  
true_cfg = 1 
id_weight = 1
timestep_to_start_cfg = 1
max_sequence_length = 128

3. After running the program, a bug appeared:
Traceback (most recent call last):
  File "/root/backend/task/PuLID/preparation/run_inference.py", line 86, in <module>
    output_image, seed_output, intermediate_output = generator.generate_image(
  File "/root/miniconda3/envs/PuLID/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/backend/task/./PuLID/process_task/app_flux.py", line 161, in generate_image
    x = self.ae.decode(x)
  File "/root/backend/task/./PuLID/PuLID/flux/modules/autoencoder.py", line 309, in decode
    return self.decoder(z)
  File "/root/miniconda3/envs/PuLID/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/backend/task/./PuLID/PuLID/flux/modules/autoencoder.py", line 253, in forward
    h = self.up[i_level].upsample(h)
  File "/root/miniconda3/envs/PuLID/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/backend/task/./PuLID/PuLID/flux/modules/autoencoder.py", line 104, in forward
    x = nn.functional.interpolate(x, scale_factor=2.0, mode="nearest")
  File "/root/miniconda3/envs/PuLID/lib/python3.10/site-packages/torch/nn/functional.py", line 3931, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
RuntimeError: "upsample_nearest2d_out_frame" not implemented for 'BFloat16'

The code segment that involves the bug is:
with torch.autocast(device_type=self.device.type, dtype=torch.bfloat16):
            x = self.ae.decode(x)

**Comment by ToTheBeginning** [comment]
Please refer to https://github.com/ToTheBeginning/PuLID/issues/90
