### ISSUE TITLE
Error when run python app.py

### ISSUE THREAD

**Issue by omidud** [ToTheBeginning/PuLID#186]
I follow the instructions using anaconda
everything look good but
when i run python app.py

(pulid) C:\lipsync\PuLID>python app.py
Traceback (most recent call last):
  File "C:\lipsync\PuLID\app.py", line 6, in <module>
    from pulid.pipeline import PuLIDPipeline
  File "C:\lipsync\PuLID\pulid\pipeline.py", line 7, in <module>
    from diffusers import (
  File "C:\Users\omidu\.conda\envs\pulid\lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "C:\Users\omidu\.conda\envs\pulid\lib\site-packages\diffusers\utils\__init__.py", line 37, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "C:\Users\omidu\.conda\envs\pulid\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (C:\Users\omidu\.conda\envs\pulid\lib\site-packages\huggingface_hub\__init__.py)

**Comment by firofame** [comment]
same error

`cannot import name 'cached_download' from 'huggingface_hub'`

**Comment by AFMSB** [comment]
change your requirements from this:

`diffusers==0.25.0`

to this:

`diffusers>=0.29.0`

and it should be fixed

> same error
> 
> `cannot import name 'cached_download' from 'huggingface_hub'`
