### ISSUE TITLE
ERROR:    Exception in ASGI application

### ISSUE THREAD

**Issue by gebaltso** [ToTheBeginning/PuLID#61]
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File ".../conda_envs/pulid/lib/python3.10/site-packages/pydantic/type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File ".../conda_envs/pulid/lib/python3.10/site-packages/pydantic/type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__
```

Can anyone help with this issue?

**Comment by phreaker0** [comment]
@gebaltso there is regression with some libraries. I fixed it by using older versions:

- add the following lines to "requirements.txt"

```
pydantic==2.8.2
pydantic-core==2.20.1
fastapi==0.112.4
```

- run pip install again

`pip install -r requirements.txt`

**Comment by gebaltso** [comment]
> @gebaltso there is regression with some libraries. I fixed it by using older versions:
> 
> * add the following lines to "requirements.txt"
> 
> ```
> pydantic==2.8.2
> pydantic-core==2.20.1
> fastapi==0.112.4
> ```
> 
> * run pip install again
> 
> `pip install -r requirements.txt`

Thanks a lot! It indeed worked.

**Comment by a21211** [comment]
great! solve my problem
