### ISSUE TITLE
Cuda missing from requirements.txt

### ISSUE THREAD

**Issue by brentjohnston** [ToTheBeginning/PuLID#7]
Here was the error when using powershell, creating venv, following instruction and installing the requirements.txt, and running python app.py

```
C:\users\newpc\downloads\pullid\pulid\venv\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Please 'pip install xformers'
Please 'pip install apex'
Please 'pip install xformers'
C:\users\newpc\downloads\pullid\pulid\venv\lib\site-packages\diffusers\configuration_utils.py:244: FutureWarning: It is deprecated to pass a pretrained model name or path to `from_config`.If you were trying to load a model, please use <class 'diffusers.models.unet_2d_condition.UNet2DConditionModel'>.load_config(...) followed by <class 'diffusers.models.unet_2d_condition.UNet2DConditionModel'>.from_config(...) instead. Otherwise, please make sure to pass a configuration dictionary instead. This functionality will be removed in v1.0.0.
  deprecate("config-passed-as-path", "1.0.0", deprecation_message, standard_warn=False)
Traceback (most recent call last):
  File "C:\users\newpc\downloads\pullid\pulid\app.py", line 11, in <module>
    pipeline = PuLIDPipeline()
  File "C:\users\newpc\downloads\pullid\pulid\pulid\pipeline.py", line 42, in __init__
    unet = UNet2DConditionModel.from_config(sdxl_base_repo, subfolder='unet').to(self.device, torch.float16)
  File "C:\users\newpc\downloads\pullid\pulid\venv\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "C:\users\newpc\downloads\pullid\pulid\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\users\newpc\downloads\pullid\pulid\venv\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\users\newpc\downloads\pullid\pulid\venv\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\users\newpc\downloads\pullid\pulid\venv\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
(venv) PS C:\users\newpc\downloads\pullid\pulid>
```

I was able to resolve with:
`pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118`

Just in case anyone else also runs into this issue. It's downloading now but still mentions the diffusers.models.unet_2d_condition.UNet2dconditionModel message.

```
C:\users\newpc\downloads\pullid\pulid\venv\lib\site-packages\diffusers\configuration_utils.py:244: FutureWarning: It is deprecated to pass a pretrained model name or path to `from_config`.If you were trying to load a model, please use <class 'diffusers.models.unet_2d_condition.UNet2DConditionModel'>.load_config(...) followed by <class 'diffusers.models.unet_2d_condition.UNet2DConditionModel'>.from_config(...) instead. Otherwise, please make sure to pass a configuration dictionary instead. This functionality will be removed in v1.0.0.
  deprecate("config-passed-as-path", "1.0.0", deprecation_message, standard_warn=False)
sdxl_lightning_4step_unet.safetensors:   8%|██▋                                 | 388M/5.14G [00:31<06:11, 12.8MB/s]
```

**Comment by brentjohnston** [comment]
Also is there anyway I can use a custom diffusers model I trained? I am unsure where to place it.
