### ISSUE TITLE
Getting Error when starting it

### ISSUE THREAD

**Issue by TomiTom1234** [ToTheBeginning/PuLID#82]
When I try to start the tool, using the command "python app.py", I get this error code:

`Traceback (most recent call last):
  File "D:\AI\PuLID\app.py", line 6, in <module>
    from pulid.pipeline import PuLIDPipeline
  File "D:\AI\PuLID\pulid\pipeline.py", line 4, in <module>
    import insightface
  File "C:\Users\abu-m\miniconda3\envs\pulid\lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "C:\Users\abu-m\miniconda3\envs\pulid\lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "C:\Users\abu-m\miniconda3\envs\pulid\lib\site-packages\insightface\app\mask_renderer.py", line 4, in <module>
    import albumentations as A
  File "C:\Users\abu-m\miniconda3\envs\pulid\lib\site-packages\albumentations\__init__.py", line 6, in <module>
    from .augmentations import *
  File "C:\Users\abu-m\miniconda3\envs\pulid\lib\site-packages\albumentations\augmentations\__init__.py", line 1, in <module>
    from .blur.functional import *
  File "C:\Users\abu-m\miniconda3\envs\pulid\lib\site-packages\albumentations\augmentations\blur\__init__.py", line 1, in <module>
    from .functional import *
  File "C:\Users\abu-m\miniconda3\envs\pulid\lib\site-packages\albumentations\augmentations\blur\functional.py", line 9, in <module>
    from albucore.utils import clipped, maybe_process_in_chunks, preserve_channel_dim
ImportError: cannot import name 'preserve_channel_dim' from 'albucore.utils' (C:\Users\abu-m\miniconda3\envs\pulid\lib\site-packages\albucore\utils.py)`

Any idea how to solve this?

**Comment by Peter5Chiou** [comment]
just downgrade
`pip install albucore==0.0.16`

**Comment by ToTheBeginning** [comment]
Maybe you can refer to this issue https://github.com/Gourieff/comfyui-reactor-node/issues/426
